#!/bin/sh

# Mount filesystems
mount -t devtmpfs dev /dev
mount -t proc proc /proc
mount -t sysfs sys /sys
mkdir /dev/pts
mount -t devpts devpts /dev/pts

# Initialize network
sh /etc/rc &

# Start shell on the console
while true; do
	echo New shell
	setsid sh -c 'exec sh < /dev/ttyAMA0 > /dev/ttyAMA0 2>&1'
done
